spring.application.name=tiendaaccesorios
spring.datasource.url=jdbc:mysql://localhost:3306/tienda_accesorios
spring.datasource.username=root
spring.datasource.password=261402Alice+

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080